<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([

            [
                'id' => 1,
                'name' => 'Sienna Curved Sofa - Beige Linen',
                'description' => 'Structure in metal and wood with variable density polyurethane foam padding and molded polyurethane. Encased in protective laminated fabric. Backrest and armrest with layer in sterilized goose down.',
                'length' => 220,
                'width' => 200,
                'height' => 120,
                'unit' => 'cm',
                'price' => 18999000,
                'stock' => 5,
                'label' => 'premium collection',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 2,
                'name' => 'Belvedere Sofa - Ivory Boucle',
                'description' => 'Modular curved sofa with deep seating and soft boucle upholstery. Designed for luxurious lounging with sculptural contemporary aesthetics.',
                'length' => 260,
                'width' => 105,
                'height' => 78,
                'unit' => 'cm',
                'price' => 21999000,
                'stock' => 3,
                'label' => 'best seller',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 3,
                'name' => 'Capri Squared Chair - Ash Fabric',
                'description' => 'Structure with wood and molded polyurethane foam padding, encased in protective laminated fabric. Balanced proportions and enveloping lines evoke a refined contemporary sensibility – sophisticated aesthetic elegance that is never ostentatious.',
                'length' => 80,
                'width' => 60,
                'height' => 64,
                'unit' => 'cm',
                'price' => 2499000,
                'stock' => 12,
                'label' => 'modern essential',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 4,
                'name' => 'Justine Dining Chair - Beige Oak',
                'description' => 'Structure in solid Canaletto walnut with raw-wood effect, natural finish, or stained walnut extra finish. Seat in wood with variable density polyurethane foam padding with top layer in sterilized goose-down.',
                'length' => 58,
                'width' => 62,
                'height' => 82,
                'unit' => 'cm',
                'price' => 3299000,
                'stock' => 8,
                'label' => 'artisan collection',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 5,
                'name' => 'Avalon Dining Chair - Black Leather',
                'description' => 'Structure in metal with burnished, glossy anthracite, matt titanium 710, white 100 or matt white 160 finish. Seat in wood with variable density polyurethane foam padding, with outer layer in sterilized goose-down.',
                'length' => 63,
                'width' => 58,
                'height' => 84,
                'unit' => 'cm',
                'price' => 3999000,
                'stock' => 7,
                'label' => 'premium leather',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 6,
                'name' => 'Wonban Dining Table',
                'description' => 'The disc dining table is a modern reinterpretation of the simplicity of Gangwon-do Soban. The simple form without artifice naturally blends with the grain of the wood and the texture of the leather, creating a new sense of appreciation.',
                'length' => 110,
                'width' => 110,
                'height' => 75,
                'unit' => 'cm',
                'price' => 8999000,
                'stock' => 4,
                'label' => 'signature collection',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 7,
                'name' => 'Louise Nightstand - Brown Wood',
                'description' => 'The Louise collection focuses on the dialogue between two disparate yet complementary materials: the pliable, enveloping quality of cowhide cladding and the glossy, vibrant character of glass.',
                'length' => 52,
                'width' => 45,
                'height' => 55,
                'unit' => 'cm',
                'price' => 2199000,
                'stock' => 9,
                'label' => 'luxury detail',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 8,
                'name' => 'Steel Top Dining Table',
                'description' => 'Dining table using materials of contrasting physical properties of wood and metal. Industrial-inspired contemporary design with durable steel tabletop.',
                'length' => 200,
                'width' => 90,
                'height' => 75,
                'unit' => 'cm',
                'price' => 10999000,
                'stock' => 2,
                'label' => null,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 9,
                'name' => 'Oval Stone Dining Table',
                'description' => 'The Oval dining table highlights Eastern Edition’s signature oval base and rounded-edged table top. Black granite contrasts with the natural walnut for a timeless appearance.',
                'length' => 185,
                'width' => 90,
                'height' => 75,
                'unit' => 'cm',
                'price' => 12999000,
                'stock' => 3,
                'label' => null,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 10,
                'name' => 'Ground Tea Table',
                'description' => 'Serving as a sculptural piece on its own, the tea table features a spherical walnut base that juxtaposes the lightness and weight of the glass and stone tabletop.',
                'length' => 148,
                'width' => 89,
                'height' => 41,
                'unit' => 'cm',
                'price' => 4999000,
                'stock' => 5,
                'label' => 'designer collection',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 11,
                'name' => 'Braidense Bookcase - Brown Wood',
                'description' => 'The elegance of subtraction exemplifies the Braidense bookcase whose aesthetic austerity, premium materials and fine artisan craftsmanship come together in perfect balance.',
                'length' => 160,
                'width' => 38,
                'height' => 210,
                'unit' => 'cm',
                'price' => 11999000,
                'stock' => 2,
                'label' => 'signature storage',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 12,
                'name' => 'Lucentia Lamp',
                'description' => 'A modern minimalist pendant light in a sleek black finish. Perfectly tailored for sophisticated dining rooms, culinary spaces, and contemporary cafés.',
                'length' => 19,
                'width' => 19,
                'height' => 38,
                'unit' => 'cm',
                'price' => 349000,
                'stock' => 15,
                'label' => 'best seller',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 13,
                'name' => 'Elysian Lamp',
                'description' => 'An elegant, modern minimalist pendant light crafted from premium metal and glass, designed to elevate contemporary interiors.',
                'length' => 22,
                'width' => 22,
                'height' => 150,
                'unit' => 'cm',
                'price' => 499000,
                'stock' => 10,
                'label' => 'elegant collection',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 14,
                'name' => 'Solari Lamp',
                'description' => 'A modern pendant light in pristine white. Ideal for creating a refined ambiance in living rooms, dining areas, and aesthetic cafés.',
                'length' => 25,
                'width' => 25,
                'height' => 30,
                'unit' => 'cm',
                'price' => 299000,
                'stock' => 18,
                'label' => 'minimalist decor',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 15,
                'name' => 'Midnight Bed - Khaki',
                'description' => 'The Midnight bed reinterprets the traditional bed base, reworking its lines and proportions with contemporary insight and craftsmanship details that convey couture tailoring.',
                'length' => 220,
                'width' => 190,
                'height' => 110,
                'unit' => 'cm',
                'price' => 16999000,
                'stock' => 4,
                'label' => 'premium comfort',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 16,
                'name' => 'Laurent Bed Cabinet - Mocha Wood',
                'description' => 'Vertical cabinet, chest of drawers and night stand combining clean lines, luxurious materials and exquisite construction details.',
                'length' => 60,
                'width' => 45,
                'height' => 58,
                'unit' => 'cm',
                'price' => 2999000,
                'stock' => 6,
                'label' => 'elegant bedroom',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 17,
                'name' => 'Loungescape Bed - Khaki',
                'description' => 'The Loungescape bed is defined by its sculptural, contemporary presence, seamlessly reinterpreting the spirit of the upholstered bed.',
                'length' => 235,
                'width' => 205,
                'height' => 105,
                'unit' => 'cm',
                'price' => 18999000,
                'stock' => 2,
                'label' => 'designer choice',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 18,
                'name' => 'Gregory Bed - Grey Metal',
                'description' => 'The Gregory bed rests on a metal frame and cast aluminum feet crafted in elegant finishes that offer subtle contrast to the cowhide strips.',
                'length' => 225,
                'width' => 195,
                'height' => 115,
                'unit' => 'cm',
                'price' => 17999000,
                'stock' => 3,
                'label' => 'industrial luxury',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 19,
                'name' => 'Asolo Bed - Grey Plywood',
                'description' => 'Comfortable and sophisticated, the Asolo bed reflects the same aesthetic concepts as the eponymous seating system. Generously padded with removable upholstery.',
                'length' => 215,
                'width' => 185,
                'height' => 100,
                'unit' => 'cm',
                'price' => 14999000,
                'stock' => 5,
                'label' => 'modern comfort',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 20,
                'name' => 'Rafael Cabinet - Brown Oak',
                'description' => 'Vertical cabinet, chest of drawers and night stand. The structure, like the drawer and door fronts, is in ash with glossy mocha color lacquer finish, while the marble top features an unusual diamond cut that, along with the metal drawer pulls.',
                'length' => 80,
                'width' => 54,
                'height' => 100,
                'unit' => 'cm',
                'price' => 2499000,
                'stock' => 7,
                'label' => null,
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}